Repository study-for-code/Frontend, pull requests merged in 2024-06, with the labels that each got.

#3 design: 홈페이지 디자인
  src/App.css
  src/App.tsx
  src/assets/home/category_expansion.png
  src/assets/home/category_expansion2.png
  src/assets/home/expansion.png
  src/assets/home/goormThinking.jpg
  src/assets/home/hamburgerBar.png
  src/assets/home/logout.png
  src/assets/home/plus.png
  src/font/GmarketSansTTFBold.ttf
  src/font/GmarketSansTTFLight.ttf
  src/font/GmarketSansTTFMedium.ttf
  src/index.css
  src/main.tsx
  src/styles/common/ColorStyles.ts
  src/styles/common/GlobalFonts.ts
  src/styles/home/homeStyles.ts
  src/styles/keyframes.ts
  vite.config.ts
Labels: Design

#4 [Feat] 코드 리뷰 관리 기능
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.tsx
  src/components/AlgorithmList.tsx
  src/components/CodeReview.tsx
  src/constants/TaskList.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/styles/common/ColorStyles.ts
  src/styles/common/GlobalFonts.ts
  src/styles/home/CodeReviewStyles.ts
  src/styles/home/homeStyles.ts
  src/styles/keyframes.ts
  src/types/aboutHome.ts
Labels: Design, Feat

#6 [Docs] 라우팅 추가, 타입 오류 해결
  src/App.tsx
  src/components/CodeReview.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/types/aboutHome.ts
Labels: Bugfix, Docs

#7 feat: 로그인, 회원가입 페이지 퍼블리싱 및 다수 잡다한 작업 완료
  src/App.tsx
  src/assets/login/eye-closed.png
  src/assets/login/eye.png
  src/assets/login/social_kakao.png
  src/assets/login/study_for_code.png
  src/assets/signup/eye-closed.png
  src/assets/signup/eye.png
  src/atom/stats.ts
  src/components/home/HamburgerBar.tsx
  src/components/login/DivideSection.tsx
  src/components/login/InputSection.tsx
  src/components/login/KakaoBtnSection.tsx
  src/components/login/SignupSection.tsx
  src/components/login/TitleContainer.tsx
  src/components/login/WrongMentContainer.tsx
  src/components/signup/SignupInputSection.tsx
  src/hooks/home/useGetCategoryData.tsx
  src/hooks/home/useHandleToggle.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Singnup/Singup.tsx
  src/styles/common/ColorStyles.ts
  src/styles/common/inputStyles.ts
  src/styles/login/loginStyles.ts
  src/styles/signup/signupStyles.ts
  src/types/aboutHome.ts
  src/types/aboutLogin.ts
Labels: Design

#11 [Feat] 스터디 삭제, 입장 모달 구현, recoil 적용
  src/assets/home/pen.png
  src/assets/home/trash.png
  src/atom/stats.ts
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/modal/CreateStudyModal.tsx
  src/components/modal/DeleteStudyModal.tsx
  src/components/modal/EnterStudyModal.tsx
  src/constants/StudyList.ts
  src/mocks/handlers.ts
  src/pages/Home/Home.tsx
  src/styles/home/homeStyles.ts
  src/styles/modal/CreateStudyStyles.ts
  src/styles/modal/modalStyles.ts
  src/types/aboutStudy.ts
Labels: Feat

#12 [Feat] 코드 리뷰 수정사항 반영, User Grade 추가, Study_id 추가, [Refactor] API custom Hook 반영
  src/assets/home/admin.png
  src/atom/stats.ts
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/modal/CreateStudyModal.tsx
  src/components/modal/EnterStudyModal.tsx
  src/constants/StudyList.ts
  src/constants/UserData.ts
  src/hooks/home/useGetFullStudyData.tsx
  src/hooks/home/useGetStudyData.tsx
  src/hooks/home/useGetUserData.tsx
  src/pages/Home/Home.tsx
  src/styles/home/homeStyles.ts
  src/types/User.ts
  src/types/aboutStudy.ts
Labels: Feat, Refactor

#14 feat: 문제 생성, 관리 페이지 퍼블리싱
  src/App.tsx
  src/assets/admin/Clock_fill.png
  src/assets/admin/Expand_left_double.png
  src/assets/admin/Expand_right_double.png
  src/assets/admin/Folder_fill.png
  src/assets/admin/Percent.png
  src/assets/admin/Status_list.png
  src/assets/admin/Time_fill.png
  src/assets/admin/casual_man.png
  src/assets/admin/list.png
  src/assets/react.svg
  src/components/admin/CreateProblems.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/ProblemList.tsx
  src/components/admin/ManageProblems/SlideModalNavBar.tsx
  src/components/admin/UserWithdrawral.tsx
  src/components/home/StudyList.tsx
  src/components/login/TitleContainer.tsx
  src/constants/TaskList.ts
  src/constants/problemList.ts
  src/hooks/admin/useManageProblemData.tsx
  src/mocks/handlers.ts
  src/pages/Admin/Admin.tsx
  src/pages/Login/Login.tsx
  src/styles/admin/adminStyles.ts
  src/styles/admin/userWithDrawralStyles.tsx
  src/styles/common/ColorStyles.ts
  src/styles/login/loginStyles.ts
  src/types/aboutAdmin.ts
Labels: Design, Feat

#15 [Feat] 카테고리 추가 기능 구현, Modal 스타일 적용
  .prettierrc
  src/assets/home/plus_gray.png
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/modal/CreateCategoryModal.tsx
  src/components/modal/CreateStudyModal.tsx
  src/components/modal/DeleteStudyModal.tsx
  src/components/modal/EnterStudyModal.tsx
  src/styles/common/ColorStyles.ts
  src/styles/home/homeStyles.ts
  src/styles/modal/modalStyles.ts
Labels: Design, Feat

#16 style: optionsContainer, modal input 스타일링
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/modal/CreateStudyModal.tsx
  src/styles/home/homeStyles.ts
  src/styles/modal/modalStyles.ts
Labels: Design

#17 [Feat] 카테고리 제목 수정 기능 구현
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/modal/CreateCategoryModal.tsx
  src/components/modal/CreateStudyModal.tsx
  src/styles/home/homeStyles.ts
Labels: Feat

#18 feat: 관리자 페이지 Create 연결, 상태 관리
  .gitignore
  src/App.tsx
  src/assets/admin/Close_round.png
  src/assets/admin/minus.png
  src/assets/home/plus_testCase.png
  src/components/admin/CreateProblems.tsx
  src/components/admin/CreateProblems/ProblemDetailSection.tsx
  src/components/admin/CreateProblems/ProblemInputSection.tsx
  src/components/admin/CreateProblems/TestCaseModal.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/SlideModalNavBar.tsx
  src/components/signup/SignupInputSection.tsx
  src/main.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Singnup/Signup.tsx
  src/pages/Singnup/Singup.tsx
  src/styles/admin/adminStyles.ts
  src/styles/keyframes.ts
  src/types/aboutAdmin.ts
  src/types/aboutLogin.ts
  src/types/aboutSignup.ts
Labels: Design, Feat

#19 [Feat] 회원가입 구현
  src/components/login/TitleContainer.tsx
  src/components/signup/SignupInputSection.tsx
  src/pages/Singnup/Signup.tsx
  src/styles/signup/signupStyles.ts
  src/types/aboutSignup.ts
Labels: Feat

#22 feat: 헤더에 토큰 담아서 요청, 문제 생성 및 관리 페이지 리펙토링
  src/assets/admin/File_dock.png
  src/assets/admin/check_ring_round.png
  src/components/admin/CreateProblems.tsx
  src/components/admin/CreateProblems/ProblemDetailSection.tsx
  src/components/admin/CreateProblems/ProblemInputSection.tsx
  src/components/admin/CreateProblems/TestCaseModal.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/ProblemList.tsx
  src/components/admin/ManageProblems/SlideModalNavBar.tsx
  src/components/home/CategorySpace.tsx
  src/components/home/StudyList.tsx
  src/components/modal/CreateStudyModal.tsx
  src/hooks/admin/useManageProblemData.tsx
  src/hooks/home/useGetStudyData.tsx
  src/pages/Home/Home.tsx
  src/styles/admin/adminStyles.ts
  src/types/aboutAdmin.ts
Labels: Design, Feat

#24 [Feat] 문제 수정 테스트 케이스 추가, 테스트 케이스 조회 및 수정
  src/components/AlgorithmList.tsx
  src/components/CodeReview.tsx
  src/components/admin/CreateProblems.tsx
  src/components/admin/CreateProblems/TestCaseModal.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/SlideModalNavBar.tsx
  src/components/admin/ManageProblems/TestCaseModifyModal.tsx
  src/components/home/CategorySpace.tsx
  src/components/login/WrongMentContainer.tsx
  src/components/modal/EnterStudyModal.tsx
  src/components/signup/SignupInputSection.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Login/Login.tsx
  src/styles/admin/adminStyles.ts
  src/styles/keyframes.ts
  src/styles/login/loginStyles.ts
  src/types/aboutAdmin.ts
Labels: Design, Feat

#25 [Feat] HamburgerBar animation 스타일, 검색 창
  src/components/AlgorithmList.tsx
  src/components/CodeReview.tsx
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/modal/EnterStudyModal.tsx
  src/pages/Home/Home.tsx
  src/styles/home/CodeReviewStyles.ts
  src/styles/home/SubscribeStyles.ts
  src/styles/home/homeStyles.ts
  src/styles/keyframes.ts
Labels: Design, Feat

#26 [Feat] User Section 구현, 알고리즘 설명 페이지 구현, Page atom화
  src/atom/stats.ts
  src/components/AlgorithmDescription.tsx
  src/components/CodeIDE.tsx
  src/components/CodeReview.tsx
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/home/UserSection.tsx
  src/components/modal/CreateCategoryModal.tsx
  src/hooks/home/useGetOwnerData.tsx
  src/pages/Home/Home.tsx
  src/styles/common/ColorStyles.ts
  src/styles/home/DescriptionStyles.ts
  src/styles/home/homeStyles.ts
  src/types/aboutHome.ts
Labels: Bugfix, Design, Feat, Refactor

#27 [feat]검색 구현
  package.json
  pnpm-lock.yaml
  src/assets/home/User.png
  src/assets/home/check.png
  src/assets/home/plus_white.png
  src/atom/stats.ts
  src/components/AlgorithmList.tsx
  src/components/admin/CreateProblems.tsx
  src/components/admin/CreateProblems/ProblemDetailSection.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/SlideModalNavBar.tsx
  src/components/home/AlgorithmList.tsx
  src/components/home/CodeReview.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/constants/AlgorithmListColumn.tsx
  src/hooks/admin/AlgorithmList/useGetAlgorithmList.tsx
  src/hooks/admin/CreateProblems/useInputData.tsx
  src/hooks/admin/CreateProblems/useOnCreate.tsx
  src/hooks/admin/ManageProblems/useHandleTestCaseModal.tsx
  src/hooks/admin/ManageProblems/useModifyData.tsx
  src/hooks/home/useGetCategoryData.tsx
  src/hooks/home/useHandleToggle.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Home/Home.tsx
  src/styles/admin/adminStyles.ts
  src/styles/home/SubscribeStyles.ts
  src/styles/home/algorithmStyles.ts
  src/styles/home/homeStyles.ts
  src/types/aboutAdmin.ts
  src/types/aboutHome.ts
  src/types/aboutStudy.ts
Labels: Bugfix, Design, Feat

#28 [Feat] 문제 정보 화면, 코드 IDE 입력 및 채점 기능 구현
  package.json
  pnpm-lock.yaml
  src/components/AlgorithmDescription.tsx
  src/components/CodeIDE.tsx
  src/components/CodeSpace.tsx
  src/components/home/CategorySpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/UserSection.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/hooks/home/useGetStudyData.tsx
  src/pages/Home/Home.tsx
  src/styles/home/DescriptionStyles.ts
  src/styles/home/IDEStyles.ts
  src/styles/home/homeStyles.ts
  src/types/aboutStudy.ts
Labels: Chore, Design, Feat

#29 feat: 카테고리 스크롤 추가, 서로 다른 데이터로 보여주기
  src/atom/stats.ts
  src/components/home/AlgorithmList.tsx
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/CodeReview.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/hooks/admin/AlgorithmList/useGetAlgorithmList.tsx
  src/hooks/home/CategorySpace/useHandleDeleteClick.tsx
  src/hooks/home/CategorySpace/useHandleDeleteModal.tsx
  src/hooks/home/CategorySpace/useHandleInputChange.tsx
  src/hooks/home/CategorySpace/useOnDelete.tsx
  src/hooks/home/useGetCategoryData.tsx
  src/pages/Home/Home.tsx
  src/styles/home/homeStyles.ts
  src/types/aboutHome.ts
Labels: Bugfix, Design, Feat

#30 feat: 추가 기능 오류 수정
  src/atom/stats.ts
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/hooks/admin/AlgorithmList/useGetAlgorithmList.tsx
Labels: Bugfix

#32 feat: 중간 사항 저장
  src/atom/stats.ts
  src/components/AlgorithmDescription.tsx
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/CodeReview.tsx
  src/components/home/UserSection.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/pages/Home/Home.tsx
  src/styles/home/CodeReviewStyles.ts
  src/types/aboutHome.ts
Labels: Feat

#33 fix : 전체적인 오류 및 CSS 수정
  src/atom/stats.ts
  src/components/admin/CreateProblems/ProblemDetailSection.tsx
  src/components/dashboard/AlgorithmDescription.tsx
  src/components/dashboard/CodeIDE.tsx
  src/components/dashboard/CodeSpace.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/home/UserSection.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/components/login/WrongMentContainer.tsx
  src/components/modal/CreateStudyModal.tsx
  src/components/signup/SignupInputSection.tsx
  src/hooks/admin/CreateProblems/useOnCreate.tsx
  src/hooks/code/useGetSolvedMember.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Singnup/Signup.tsx
  src/styles/home/DescriptionStyles.ts
  src/styles/home/IDEStyles.ts
  src/styles/home/algorithmStyles.ts
  src/styles/home/homeStyles.ts
  src/styles/login/loginStyles.ts
  src/styles/signup/signupStyles.ts
  src/types/aboutStudy.ts
Labels: Bugfix, Design, Refactor

#34 [Feat] 문제 리스트에서 추가된 카테고리 확인, 스터디 이미지 API 연결, 사소한 오류 수정
  src/atom/stats.ts
  src/components/dashboard/AlgorithmDescription.tsx
  src/components/dashboard/CodeIDE.tsx
  src/components/home/AlgorithmList.tsx
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/pages/Home/Home.tsx
  src/styles/home/homeStyles.ts
  src/types/aboutHome.ts
  src/types/aboutStudy.ts
Labels: Bugfix, Design, Feat

#35 [Feat]채팅, 코드 리뷰 기능 구현
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/assets/home/Expand_down_stop.png
  src/assets/home/Expand_right_stop.png
  src/atom/stats.ts
  src/components/CodeReview.tsx
  src/components/dashboard/CodeIDE.tsx
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/CodeReview.tsx
  src/components/home/CodeReview/ChatRoom.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/UserSection.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/components/modal/CreateStudyModal.tsx
  src/hooks/home/useGetCategoryData.tsx
  src/pages/Home/Home.tsx
  src/styles/home/CodeReviewStyles.ts
  src/styles/login/loginStyles.ts
  src/types/aboutCodeReview.ts
  src/types/aboutHome.ts
  tsconfig.json
  vite.config.ts
Labels: Bugfix, Chore, Design, Feat

#36 [Feat] 문제 검색 기능 구현
  src/components/home/AlgorithmList.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/styles/home/algorithmStyles.ts
Labels: Feat

#37 console.log 삭제, 배포된 서버로 도메인주소 변경
  package.json
  pnpm-lock.yaml
  src/components/admin/CreateProblems.tsx
  src/components/admin/ManageProblems.tsx
  src/components/admin/ManageProblems/TestCaseModifyModal.tsx
  src/components/dashboard/AlgorithmDescription.tsx
  src/components/dashboard/CodeIDE.tsx
  src/components/home/AlgorithmList.tsx
  src/components/home/AlgorithmList/AlgorithmListColumn.tsx
  src/components/home/CodeReview.tsx
  src/components/home/CodeReview/ChatRoom.tsx
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/components/home/UserSection.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/components/home/hamburgerBar/CategorySpace/CategoryList.tsx
  src/components/modal/EnterStudyModal.tsx
  src/components/signup/SignupInputSection.tsx
  src/hooks/admin/AlgorithmList/useGetAlgorithmList.tsx
  src/hooks/admin/CreateProblems/useOnCreate.tsx
  src/hooks/admin/ManageProblems/useHandleTestCaseModal.tsx
  src/hooks/admin/ManageProblems/useModifyData.tsx
  src/hooks/admin/useManageProblemData.tsx
  src/hooks/code/useGetSolvedMember.tsx
  src/hooks/home/CategorySpace/useOnDelete.tsx
  src/hooks/home/useGetCategoryData.tsx
  src/hooks/home/useGetOwnerData.tsx
  src/hooks/home/useGetStudyData.tsx
  src/hooks/home/useGetUserData.tsx
  src/pages/Admin/Admin.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Singnup/Signup.tsx
  vite.config.ts
Labels: Bugfix, Chore, Feat

#38 Feat: 서버에서 스터디 이미지 가져오기
  index.html
  public/favicon.ico
  src/components/home/HamburgerBar.tsx
  src/components/home/StudyList.tsx
  src/styles/home/homeStyles.ts
Labels: Design, Feat

#42 [Bugfix]배포 오류 수정
  src/components/CodeReview.tsx
  src/components/dashboard/AlgorithmDescription.tsx
  src/components/home/CodeReview.tsx
  src/components/home/CodeReview/ChatRoom.tsx
  src/components/home/StudyList.tsx
  src/hooks/admin/AlgorithmList/useGetAlgorithmList.tsx
  src/hooks/admin/ManageProblems/useDeleteData.tsx
Labels: Bugfix

#44 bugfix: 채팅 버그 수정
  src/components/admin/ManageProblems.tsx
  src/components/home/CodeReview.tsx
  src/components/home/CodeReview/ChatRoom.tsx
  src/components/home/hamburgerBar/CategorySpace.tsx
  src/styles/home/CodeReviewStyles.ts
Labels: Bugfix

#45 배포 테스트
  src/components/home/CodeReview/ChatRoom.tsx
  vite.config.ts
Labels: Chore

#46 [Build] build 방식 변경
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: Chore
